# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5cc281edfa9cdb339eac430d4c76df91b3b78639d85fd67d336545a3d280be2c80d3f532fb079b774963e9d86bb9880a1e4ca288c97cf50afa97dac43cedb26

test:
  secret_key_base: 35b7c7e8a449072b9b847078d54838a3f2c11833eee36fcdeaedac6f92f045232443aa2e6afdca90015b4e1725b57406eebc6f87b41aae0ffafcd803370a9e13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
